// Minimax 官方账号
let MINIMAX_API_KEY = process.env.UMI_MINIMAX_API_KEY || '';
let MINIMAX_TTS_API_HOST = process.env.UMI_MINIMAX_TTS_API_HOST || '';
let MINIMAX_GROUPID = process.env.UMI_MINIMAX_GROUPID || '';

let openAIBaseURL = 'https://' + process.env.UMI_NEXT_PUBLIC_PROD_API_HOST + '/v1/';
let transcriptURL = 'https://' + process.env.UMI_NEXT_PUBLIC_PROD_API_HOST + '/302/transcript?url=';
let OPENAI_AUDIO_TO_TEXT_API = process.env.UMI_NEXT_PUBLIC_PROD_OPENAI_AUDIO_TO_TEXT_API || '';
let OPENAI_SPEAKER_TTS_API = process.env.UMI_NEXT_PUBLIC_PROD_OPENAI_SPEAKER_TTS_API || '';
let MOON_SPEAKER_TTS_API = process.env.UMI_NEXT_PUBLIC_PROD_MOON_SPEAKER_TTS_API || '';
let MINIMAX_SPEAKER_TTS_API = process.env.UMI_NEXT_PUBLIC_PROD_MINIMAX_SPEAKER_TTS_API || '';
let MINIMAX_SPEAKER_STATUS_API = process.env.UMI_NEXT_PUBLIC_PROD_MINIMAX_SPEAKER_STATUS_API || '';
let MINIMAX_SPEAKER_DOWNLOAD_API = process.env.UMI_NEXT_PUBLIC_PROD_MINIMAX_SPEAKER_DOWNLOAD_API || '';
let API_KEY = process.env.UMI_NEXT_PUBLIC_API_KEY || '';
let REGION = process.env.UMI_NEXT_PUBLIC_REGION || '';
let UPLOAD_API = process.env.UMI_NEXT_PUBLIC_UPLOAD_API || '';


export {
  API_KEY,
  MINIMAX_SPEAKER_DOWNLOAD_API,
  MINIMAX_SPEAKER_STATUS_API,
  MINIMAX_SPEAKER_TTS_API,
  MINIMAX_API_KEY,
  MINIMAX_GROUPID,
  MINIMAX_TTS_API_HOST,
  MOON_SPEAKER_TTS_API,
  OPENAI_AUDIO_TO_TEXT_API,
  OPENAI_SPEAKER_TTS_API,
  REGION,
  UPLOAD_API,
  openAIBaseURL,
  transcriptURL,
};